export const COLORS = {
  BACKGROUND: '#FFFFFF',
  PRIMARY_BUTTON: '#3897F0',
  SECONDARY_BUTTON: '#A3A3A3',
  PRIMARY_TEXT: '#000000',
  SECONDARY_TEXT: '#FFFFFF',
  LABEL_TEXT: '#CCCCCC',
  ERROR: '#990000',
  INPUT: '#B3B9BD',
};
